---
title: "Battle in Atlantic"
author: "Tapas Mishra"
date: "18 April 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
setwd("C:/Users/TAPAS/Documents")
dataset <- read.csv("./sinkingstats-1.csv", head = FALSE)
colnames(dataset) <- c("Date", "NorthAtlantic", "RestofWorld")
summary(dataset)
```

First , Let us create a plot area

```{r fig.height=7, fig.width=8, message=FALSE, warning=FALSE}

plot.new()
plot.window(xlim = c(0, 71), ylim = c(0, 900),xaxs="i", yaxs="i")

usr <- par("usr")
rect(usr[1], usr[3], usr[2], usr[4], col = "lemonchiffon", border = "gray")

#y-axis
axis(2, at = seq(0, 900, length = 10), las = 1, font = 2)

# Draw X axis

axis(1, at = seq(0, 71, by = 3), 
     labels = dataset$Date[seq(0, 71, by = 3) + 1], las = 2, 
     font = 2,cex.axis = 0.8,
     tck = -0.01, padj = 1)
```

Now, lets add grid lines

```{r fig.width=8, fig.height=7, message=FALSE, warning=FALSE}
plot.new()
plot.window(xlim = c(0, 71), ylim = c(0, 900),xaxs="i", yaxs="i")

usr <- par("usr")
rect(usr[1], usr[3], usr[2], usr[4], col = "lemonchiffon", border = "gray")

#y-axis
axis(2, at = seq(0, 900, length = 10), las = 1, font = 2)

# Draw X axis

axis(1, at = seq(0, 71, by = 3), 
     labels = dataset$Date[seq(0, 71, by = 3) + 1], las = 2, 
     font = 2,cex.axis = 0.8,
     tck = -0.01, padj = 1)
# Draw grid lines

abline(h = seq(100, 800, length = 8))


```

Now , Let us add bar plot to the plot area.

```{r fig.width=8, fig.height=7, message=FALSE, warning=FALSE}
plot.new()
plot.window(xlim = c(0, 71), ylim = c(0, 900),xaxs="i", yaxs="i")

usr <- par("usr")
rect(usr[1], usr[3], usr[2], usr[4], col = "lemonchiffon", border = "gray")

#y-axis
axis(2, at = seq(0, 900, length = 10), las = 1, font = 2)

# Draw X axis

axis(1, at = seq(0, 71, by = 3), 
     labels = dataset$Date[seq(0, 71, by = 3) + 1], las = 2, 
     font = 2,cex.axis = 0.8,
     tck = -0.01, padj = 1)
# Draw grid lines

abline(h = seq(100, 800, length = 8))

#Create bar plot
bar.stacked <- rbind(dataset$NorthAtlantic, dataset$RestofWorld)
barplot(bar.stacked, col = c("red", "burlywood1"), axes = FALSE, add = TRUE,space = 0)
```

and add legends....

```{r fig.width=8, fig.height=7, message=FALSE, warning=FALSE}
plot.new()
plot.window(xlim = c(0, 71), ylim = c(0, 900),xaxs="i", yaxs="i")

usr <- par("usr")
rect(usr[1], usr[3], usr[2], usr[4], col = "lemonchiffon", border = "gray")

#y-axis
axis(2, at = seq(0, 900, length = 10), las = 1, font = 2)

# Draw X axis

axis(1, at = seq(0, 71, by = 3), 
     labels = dataset$Date[seq(0, 71, by = 3) + 1], las = 2, 
     font = 2,cex.axis = 0.8,
     tck = -0.01, padj = 1)
# Draw grid lines

abline(h = seq(100, 800, length = 8))

#Create bar plot
bar.stacked <- rbind(dataset$NorthAtlantic, dataset$RestofWorld)
barplot(bar.stacked, col = c("red", "burlywood1"), axes = FALSE, add = TRUE,space = 0)

#add Legends

legend(47, 850, c("Rest of World", "North Atlantic"), bg = "white",
text.font = c(2, 2), cex = 1.2, fill = c("burlywood1", "red"))
```

Now, add comment boxes

```{r fig.width=10, fig.height=7, message=FALSE, warning=FALSE}
plot.new()
plot.window(xlim = c(0, 71), ylim = c(0, 900),xaxs="i", yaxs="i")

usr <- par("usr")

rect(usr[1], usr[3],
     
     usr[2], usr[4], col = "lemonchiffon", border = "gray")

#y-axis
axis(2, at = seq(0, 900, length = 10), las = 1, font = 2)

# Draw X axis

axis(1, at = seq(0, 71, by = 3), 
     
     labels = dataset$Date[seq(0, 71, by = 3) + 1], las = 2, 
     font = 2,cex.axis = 0.8,
     tck = -0.01, padj = 1)

# Draw grid lines

abline(h = seq(100, 800, length = 8))

bar.stacked <- rbind(dataset$NorthAtlantic, dataset$RestofWorld)

barplot(bar.stacked, col = c("red", "burlywood1"), axes = FALSE, add = TRUE,space = 0)

#add Legends

legend(47, 850, c("Rest of World", "North Atlantic"), bg = "white",
text.font = c(2, 2), cex = 1.2, fill = c("burlywood1", "red"))

#add comment box

legend(54, 500, legend = c("Capture of", "papers", "from U559"), bg = "white", 
       text.font = 2, cex = 1.4, adj = c(0.2, 0.1), box.lwd = 2)
```
Finally add arrows and plot tittle

```{r fig.height=7, fig.width=10, message=FALSE, warning=FALSE}
plot.new()
plot.window(xlim = c(0, 71), ylim = c(0, 900),xaxs="i", yaxs="i")

usr <- par("usr")

rect(usr[1], usr[3],
     
     usr[2], usr[4], col = "lemonchiffon", border = "gray")

#y-axis
axis(2, at = seq(0, 900, length = 10), las = 1, font = 2)

# Draw X axis

axis(1, at = seq(0, 71, by = 3), 
     
     labels = dataset$Date[seq(0, 71, by = 3) + 1], las = 2, 
     font = 2,cex.axis = 0.8,
     tck = -0.01, padj = 1)

# Draw grid lines

abline(h = seq(100, 800, length = 8))

bar.stacked <- rbind(dataset$NorthAtlantic, dataset$RestofWorld)

barplot(bar.stacked, col = c("red", "burlywood1"), axes = FALSE, add = TRUE,space = 0)

#add Legends

legend(47, 850, c("Rest of World", "North Atlantic"), bg = "white",
text.font = c(2, 2), cex = 1.2, fill = c("burlywood1", "red"))

#add comment box

legend(54, 500, legend = c("Capture of", "papers", "from U559"), bg = "white", 
       text.font = 2, cex = 1.4, adj = c(0.2, 0.1), box.lwd = 2)

# add arrow

arrows(x0 = 54, y0 = 400, x1 = 39.1, y1 = 200, length = 0.15,
angle = 15, code = 2, lwd = 4)

# Add title
title(main = " Shipping sunk by German U-boats against Allied shipping in World War II",text.font = 5)
```

